### ISSUE TITLE
Angular 15 with Angularfire App-Check

### ISSUE THREAD

**Issue by georgstrieder** [Di-Strix/angular-quizee#44]
How did you get Angular 15 with app-check to run? I can't get it to work. Do you have a tip? ;)

**Comment by Di-Strix** [comment]
Hello!

It is just worked for me :)

What error do you get? 

There might be some issues with `angularFire` at all if you use `compat` API of `agularFire` as it is does not work properly with Angular 15. `angularFire` has really poor documentation and it is quite hard to get what API you should use and what the differences between them. Just make sure you use `modular` API (just import stuff not from `compat` subdirectory of `angularFire`).

**Comment by Di-Strix** [comment]
Strange...
Do you provide your module with Firebase App using `provideFirebaseApp(() => initializeApp(<Firebase config>))`?

Where do you get this error (I mean is it thrown when component calls firebase API or just during App load)? 
Can you tell me the component structure of your project?

**Comment by Di-Strix** [comment]
So I will close this issue as it is not related to this project
